# Generated by Django 3.0.8 on 2020-07-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profil_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('username', models.CharField(max_length=200)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=1500, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('like', models.PositiveSmallIntegerField(default=0)),
                ('deslike', models.PositiveSmallIntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_core.Autor')),
                ('tags', models.ManyToManyField(to='system_core.Tag')),
            ],
        ),
    ]
