# Generated by Django 3.0.8 on 2020-07-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(max_length=1500, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('like', models.PositiveSmallIntegerField(default=0)),
                ('deslike', models.PositiveSmallIntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_core.Autor')),
                ('tags', models.ManyToManyField(to='system_core.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Khatira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.CharField(max_length=1500, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('like', models.PositiveSmallIntegerField(default=0)),
                ('deslike', models.PositiveSmallIntegerField(default=0)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_core.Autor')),
                ('tags', models.ManyToManyField(to='system_core.Tag')),
            ],
        ),
    ]
