# Generated by Django 3.0.8 on 2020-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0002_khatira_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='url',
            field=models.CharField(max_length=150),
        ),
    ]
