# Generated by Django 3.0.8 on 2020-07-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0003_auto_20200721_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='khatira',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sound',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
    ]
