# Generated by Django 3.0.8 on 2020-07-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0005_auto_20200722_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='khatira',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sound',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
