# Generated by Django 3.0.8 on 2020-07-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0007_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('HTML', models.TextField()),
            ],
        ),
    ]
