# Generated by Django 3.0.8 on 2020-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0008_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='actif',
            field=models.BooleanField(default=2),
            preserve_default=False,
        ),
    ]
