# Generated by Django 3.0.8 on 2020-07-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0009_sidebar_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
