# Generated by Django 3.0.8 on 2020-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0010_auto_20200724_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='actif',
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
