# Generated by Django 3.0.8 on 2020-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_core', '0012_auto_20200729_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidebar',
            name='s',
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='HTML',
            field=models.TextField(),
        ),
    ]
